kelihi_dbt:
  target: dev
  outputs: 
    dev:
      type: postgres
      host: database-1.ck7iwjg6mbq7.us-east-1.rds.amazonaws.com
      user: postgres
      password: t]L*p5O^{lr(F++dluBHfm[eBMK8]
      port: 5432
      schema: dbt_dev
      dbname: postgres
      threads: 4