services:

  kelihi_dagster:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kelihi_dagster
    image: kelihi_dagster
    ports:
      - 3000:3000
    environment:
      DAGSTER_HOME: /opt/dagster/dagster_home
    volumes:
      - ./dagster_home:/opt/dagster/dagster_home

#   dagster-webserver:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     ports:
#       - 3000:3000

#   dagster-daemon:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     command: "dagster-daemon run"
