# Dagster libraries to run both dagster-webserver and the dagster-daemon. Does not
# need to have access to any pipeline code.

FROM python:3.9-slim

RUN pip install \
    dagster==1.4.7 \
    dagster-graphql==1.4.7 \
    dagster-webserver==1.4.7 \
    dagster-postgres==0.20.7 \
    dagster-docker==0.20.7 \
    dagster-dbt==0.20.7


# Set $DAGSTER_HOME and copy dagster instance and workspace YAML there
ENV DAGSTER_HOME=/opt/dagster/dagster_home/

RUN mkdir -p $DAGSTER_HOME

COPY dagster.yaml workspace.yaml $DAGSTER_HOME

WORKDIR $DAGSTER_HOME